# Generated by Django 5.1 on 2024-08-19 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('keyboard_activity', models.IntegerField(help_text='Number of key presses')),
                ('mouse_activity', models.IntegerField(help_text='Number of mouse clicks')),
            ],
            options={
                'verbose_name_plural': 'Input Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('connection_type', models.CharField(help_text='Type of connection, e.g., HTTP, FTP', max_length=50)),
                ('inbound_traffic', models.FloatField(help_text='Inbound traffic in MB')),
                ('outbound_traffic', models.FloatField(help_text='Outbound traffic in MB')),
                ('data_transfer_rate', models.FloatField(help_text='Data transfer rate in MB/s')),
                ('active_connections', models.IntegerField(help_text='Number of active connections')),
            ],
            options={
                'verbose_name_plural': 'Network Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField(help_text='CPU usage as a percentage')),
                ('memory_usage', models.FloatField(help_text='Memory usage in MB')),
                ('disk_activity', models.FloatField(help_text='Disk activity in MB/s')),
                ('network_bandwidth', models.FloatField(help_text='Network bandwidth usage in Mbps')),
            ],
            options={
                'verbose_name_plural': 'System Performance',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(help_text='Type of alert, e.g., High CPU Usage, Unusual Network Activity', max_length=100)),
                ('threshold_value', models.FloatField(help_text='Threshold value to trigger the alert')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the alert is currently active or not')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualizationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_type', models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('pie', 'Pie')], help_text='Type of graph for data visualization', max_length=50)),
                ('time_interval', models.DurationField(help_text='Time interval for data aggregation')),
                ('display_historical_data', models.BooleanField(default=True, help_text='Whether to display historical data or not')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Visualization Preferences',
                'ordering': ['user'],
            },
        ),
    ]
